# syntax docker/dockerfile:1

FROM node:16.6

WORKDIR /app

RUN mkdir -p /app/data

COPY ["package.json", "./"]

RUN npm install

COPY . .

ARG APPLICATION_ID
ARG BOT_TOKEN
ARG BOT_USER
ARG COMMANDS_DIR
ARG FEATURES_DIR
ARG DISCORD_BASE_API
ARG GUILD_ID
ARG SECONDS_TO_DELETE_MESSAGE
ARG BOT_OWNER
ARG VPW_DATA_SERVICE_API_URI

ENV APPLICATION_ID $APPLICATION_ID
ENV BOT_TOKEN $BOT_TOKEN
ENV BOT_USER $BOT_USER
ENV COMMANDS_DIR $COMMANDS_DIR
ENV FEATURES_DIR $FEATURES_DIR
ENV DISCORD_BASE_API $DISCORD_BASE_API
ENV GUILD_ID $GUILD_ID
ENV SECONDS_TO_DELETE_MESSAGE $SECONDS_TO_DELETE_MESSAGE
ENV BOT_OWNER $BOT_OWNER
ENV VPW_DATA_SERVICE_API_URI $VPW_DATA_SERVICE_API_URI

CMD [ "node", "index.js" ]