export const createAction = (
  channelId,
  channelName,
  userId,
  username,
  link,
  version,
  comments,
  actionType,
) => ({
  channelId,
  channelName,
  userId,
  username,
  link,
  version,
  comments,
  actionType,
  created: new Date().toLocaleString("en-US", {
    month: "2-digit",
    day: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  }),
});
